# Uncomment this line to define a global platform for your project
# 指定编译iOS版本，Pods->Local Podspecs 文件中platforms指定库要求的最低iOS版本
  # spec.name             = 'Reachability' #名字
  # spec.version          = '3.1.0'	#版本
  # spec.license          = { :type => 'BSD' }	#证书
  # spec.homepage         = 'https://github.com/tonymillion/Reachability'	#首页
  # spec.authors          = { 'Tony Million' => 'tonymillion@gmail.com' }	#作者
  # spec.summary          = 'ARC and GCD Compatible Reachability Class for iOS and macOS.'	#摘要
  # spec.source           = { :git => 'https://github.com/tonymillion/Reachability.git', :tag => 'v3.1.0' }	#它的源地址
  # spec.source_files     = 'Reachability.h,m'	#要引入的文件
  # spec.framework        = 'SystemConfiguration'	#依赖的框架
  # spec.requires_arc     = true	#是否使用arc规则
  # spec.platforms        = 运行的最低版本
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
